### ISSUE TITLE
Stack overflow when indexing gap buffer

### ISSUE THREAD

**Issue by gchp** [dlaronson/gapbuffer#6]
Here's the simplest case where I can reproduce the error:

``` rust
extern crate gapbuffer

use gapbuffer::GapBuffer;

fn main() {
    let mut gb: GapBuffer<u8> = GapBuffer::new();

    gb.insert(0, 't' as u8);
    gb.insert(1, 't' as u8);

    println!("{:?}", gb[0]);
}
```

where my `Cargo.toml` contains:

``` toml
[dependencies.gapbuffer]
git = "https://github.com/dlaronson/gapbuffer"
```
